#include "PCH.h"

// Do not edit this file
// Modifying this file may cause the plugin to not load

// Global objects
EmulatorAPIManager API;
Plugin PluginInstance;

static BOOL Initialized;

BOOL APIENTRY DllMain(HINSTANCE hInstance, DWORD dwReason, LPVOID lpvReserved)
{
	switch (dwReason) {
	case DLL_PROCESS_ATTACH:

		DisableThreadLibraryCalls(hInstance);

		break;

	case DLL_PROCESS_DETACH:

		if (Initialized)
			PluginInstance.Terminate();

		break;

	default:
		__assume(0);  // No other cases exist due to DisableThreadLibraryCalls
	}

	return TRUE;
}

BOOL WINAPI PluginMain(PluginAPI::PluginInformation* Information)
{

	// Verify the parameter is the correct size
	if (Information->Size != sizeof(PluginAPI::PluginInformation))
		return FALSE;

	ZeroMemory(&API, sizeof(API));

	// Set API addresses
	// 
	// UI:
	API.m_ProcessConsoleCommand		= Information->ProcessConsoleCommand;
	API.m_RefreshUserInput			= Information->RefreshUserInput;
	API.m_ResetCursorPosition		= Information->ResetCursorPosition;
	API.m_SetOutputColor			= Information->SetOutputColor;
	API.m_WriteOutputString			= Information->WriteOutputString;
	API.m_WriteOutputTimestamp		= Information->WriteOutputTimestamp;

	// Actions:
	API.m_EventPress				= Information->EventPress;
	API.m_EventRelease				= Information->EventRelease;

	// Controller:
	API.m_GetBatteryValue			= Information->GetBatteryValue;
	API.m_GetInputValue				= Information->GetInputValue;
	API.m_GetLastInputValue			= Information->GetLastInputValue;
	API.m_GetOutputValue			= Information->GetOutputValue;
	API.m_GetPressTime				= Information->GetPressTime;
	API.m_GetReleaseTime			= Information->GetReleaseTime;
	API.m_GetRumble					= Information->GetRumble;

	// Devices:
	API.m_GetConnectedConsole		= Information->GetConnectedConsole;
	API.m_GetConnectedController	= Information->GetConnectedController;
	API.m_GetCpuLoadValue			= Information->GetCpuLoadValue;
	API.m_GetLedState				= Information->GetLedState;
	API.m_GetSlotValue				= Information->GetSlotValue;
	API.m_GetTraceValue				= Information->GetTraceValue;
	API.m_GetVmSpeedValue			= Information->GetVmSpeedValue;

	// Set hook addresses
	Information->ConnectionHook = &HookManager::ConnectionHook;
	Information->CommandHook = &HookManager::CommandHook;
	Information->DeviceHook = &HookManager::DeviceHook;
	Information->MessageHook = &HookManager::MessageHook;
	Information->HookParam = (LPARAM)&PluginInstance;

	return Initialized = PluginInstance.Initialize();
}